### ISSUE TITLE
gng resets GRADLE_OPTS environment variable

### ISSUE THREAD

**Issue by jonsmithers** [gdubw/gng#19]
**Describe the bug**
`gng` clears `GRADLE_OPTS` environment variable.

**To Reproduce**
1. Create a gradle task to help with observation
   ```groovy
   task showEnv(type:Exec) {
       commandLine 'env'
   }
   ```
1. Put _something_ in `GRADLE_OPTS`, for example, `export GRADLE_OPTS='-Dorg.gradle.daemon=false'`
1. Inspect `./gradlew showEnv | grep GRADLE_OPTS` 
1. Inspect `gw showEnv | grep GRADLE_OPTS`

**Expected behavior**
`./gradlew showEnv` and `gw showEnv` should show the same `GRADLE_OPTS`.

Actual output:

```bash
$ ./gradlew showEnv | grep GRADLE_OPTS
GRADLE_OPTS=-Dorg.gradle.daemon=false "-Xdock:name=Gradle" "-Xdock:icon=/Users/me/workspace/my-project/media/gradle.icns"
```

```bash
$ gw showEnv | grep GRADLE_OPTS
sh: SHELLOPTS: readonly variable
GRADLE_OPTS= "-Xdock:name=Gradle" "-Xdock:icon=/Users/me/workspace/my-project/media/gradle.icns"
```

**Shell Info (please complete the following information):**
 - zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by srsouto** [comment]
Confirmed, this will not clear the value of GRADLE_OPTS
