### ISSUE TITLE
Deprecation warning about calling bottle

### ISSUE THREAD

**Issue by donbex** [gdubw/gng#25]
**Describe the bug**
Using the tap with Homebrew version `3.2.17-63-g5a5a8d5` results in a deprecation warning:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the gdubw/gng tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/gdubw/homebrew-gng/Formula/gng.rb:8
```

**To Reproduce**
1. `brew update`
2. `brew tap gdubw/gng`
3. Run a Homebrew command that checks the available formulas, e.g. `brew outdated`

**Expected behavior**
No warning thrown.

**Shell Info (please complete the following information):**
 - Shell Version: zsh 5.8 (x86_64-apple-darwin19.6.0)
 - DEBUG Output: not applicable

**Comment by dantesun** [comment]
This is resolved by https://github.com/gdubw/homebrew-gng/issues/2
