### ISSUE TITLE
 Install script broken when run on WSL?

### ISSUE THREAD

**Issue by hakanai** [gdubw/gng#4]
**Describe the bug**

I tried the install instructions but get an error running the script after cloning the repo from master.

**To Reproduce**

1. Clone from master at time of writing this report
2. `cd gng`
2. `sudo ./install.sh`
3. Result:

```
$ sudo ./install.sh
./install.sh: line 2: $'\r': command not found
Failed to change to script's directory!(./install.sh)
: numeric argument required 1
```

**Expected behavior**

It would have been nice if it worked.

**Shell Info (please complete the following information):**

```
$ bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

```
$ DEBUG=1 ./bin/gng
./bin/gng: line 5: $'\r': command not found
: invalid option6: shopt: -
shopt: usage: shopt [-pqsu] [-o] [optname ...]
: invalid option7: shopt: -
shopt: usage: shopt [-pqsu] [-o] [optname ...]
./bin/gng: line 28: syntax error near unexpected token `$'in\r''
'/bin/gng: line 28: `    case "${k}" in
```

**Additional context**
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

Running WSL on latest Windows 10.

**Comment by hakanai** [comment]
It's definitely something to do with WSL. I got CRLF on the `install.sh` script when I cloned the repo. But I've cloned other repos before and haven't had a shell script do this before so this is new to me. I'll have to figure out if the other repos were preventing shell scripts from getting CRLF terminators or whether something else is up with this script specifically.

**Comment by dantesun** [comment]
I added a .gitattribute file in the repository. But I don't have Windows 10 and can't test it. Please try it out see if it helps.

**Comment by dantesun** [comment]
@hakanai I am closing this issue for now. If you have any problem after tried the '.gitattribute' file, please re-open it.
